{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "95036439-3ce7-42b7-8695-e5127add2414",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting openeo\n",
      "  Obtaining dependency information for openeo from https://files.pythonhosted.org/packages/e1/d1/5bc45bdbc80e8b3ece04838a32b9e6bdd5f9a87bb4fff7bc9238cd757b1b/openeo-0.29.0-py3-none-any.whl.metadata\n",
      "  Using cached openeo-0.29.0-py3-none-any.whl.metadata (7.3 kB)\n",
      "Collecting openeo-pg-parser-networkx\n",
      "  Obtaining dependency information for openeo-pg-parser-networkx from https://files.pythonhosted.org/packages/5a/68/a46888c84a7acb5124c3e867fe8c35c9cbf593845d30e7ed914d5c769c06/openeo_pg_parser_networkx-2024.5.0-py3-none-any.whl.metadata\n",
      "  Using cached openeo_pg_parser_networkx-2024.5.0-py3-none-any.whl.metadata (7.2 kB)\n",
      "Collecting openeo-processes-dask\n",
      "  Obtaining dependency information for openeo-processes-dask from https://files.pythonhosted.org/packages/08/ce/7238c5c1e47d1461a02351e29a3c007e410afd31acceb13df378bdd2e619/openeo_processes_dask-2024.5.3-py3-none-any.whl.metadata\n",
      "  Downloading openeo_processes_dask-2024.5.3-py3-none-any.whl.metadata (5.5 kB)\n",
      "Collecting openeo-processes\n",
      "  Obtaining dependency information for openeo-processes from https://files.pythonhosted.org/packages/08/a8/3d4c12ab6945c3cd2871f94a0bbd8a222315480ef813c3201304dc7e0d6e/openeo_processes-0.0.4-py2.py3-none-any.whl.metadata\n",
      "  Using cached openeo_processes-0.0.4-py2.py3-none-any.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: requests>=2.26.0 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from openeo) (2.32.3)\n",
      "Collecting shapely>=1.6.4 (from openeo)\n",
      "  Obtaining dependency information for shapely>=1.6.4 from https://files.pythonhosted.org/packages/81/77/e1475695606a8305c9ad5f5132d911abe8ed1655a6f5c817a69bdd2b5324/shapely-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading shapely-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.0 kB)\n",
      "Collecting numpy>=1.17.0 (from openeo)\n",
      "  Obtaining dependency information for numpy>=1.17.0 from https://files.pythonhosted.org/packages/4b/d7/ecf66c1cd12dc28b4040b15ab4d17b773b87fa9d29ca16125de01adb36cd/numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m61.0/61.0 kB\u001b[0m \u001b[31m780.1 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mMB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting xarray>=0.12.3 (from openeo)\n",
      "  Obtaining dependency information for xarray>=0.12.3 from https://files.pythonhosted.org/packages/67/91/1f55f0e026fba8eba15afb7d097bb873bd6a9e466be45a45e7cac40a930b/xarray-2024.5.0-py3-none-any.whl.metadata\n",
      "  Using cached xarray-2024.5.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting pandas>0.20.0 (from openeo)\n",
      "  Obtaining dependency information for pandas>0.20.0 from https://files.pythonhosted.org/packages/89/1b/12521efcbc6058e2673583bb096c2b5046a9df39bd73eca392c1efed24e5/pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)\n",
      "Collecting pystac>=1.5.0 (from openeo)\n",
      "  Obtaining dependency information for pystac>=1.5.0 from https://files.pythonhosted.org/packages/ee/19/f8df3ac83ae5a977b108d86c8a0d7e4ef98c91dceca136017bc183ef942e/pystac-1.10.1-py3-none-any.whl.metadata\n",
      "  Using cached pystac-1.10.1-py3-none-any.whl.metadata (6.4 kB)\n",
      "Collecting deprecated>=1.2.12 (from openeo)\n",
      "  Obtaining dependency information for deprecated>=1.2.12 from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd59ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl.metadata\n",
      "  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)\n",
      "Collecting geojson-pydantic<2.0.0,>=1.0.0 (from openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for geojson-pydantic<2.0.0,>=1.0.0 from https://files.pythonhosted.org/packages/0d/05/af6c27e0cd2f7629559db36dffc28185afb7192622ca9571d56a548038b0/geojson_pydantic-1.1.0-py3-none-any.whl.metadata\n",
      "  Using cached geojson_pydantic-1.1.0-py3-none-any.whl.metadata (4.1 kB)\n",
      "Collecting networkx<3.0.0,>=2.8.6 (from openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for networkx<3.0.0,>=2.8.6 from https://files.pythonhosted.org/packages/42/31/d2f89f1ae42718f8c8a9e440ebe38d7d5fe1e0d9eb9178ce779e365b3ab0/networkx-2.8.8-py3-none-any.whl.metadata\n",
      "  Using cached networkx-2.8.8-py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting pendulum<3.0.0,>=2.1.2 (from openeo-pg-parser-networkx)\n",
      "  Downloading pendulum-2.1.2.tar.gz (81 kB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m81.2/81.2 kB\u001b[0m \u001b[31m983.1 kB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mMB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m0:01\u001b[0m\n",
      "\u001b[?25h  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting pydantic<3.0.0,>=2.4.0 (from openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for pydantic<3.0.0,>=2.4.0 from https://files.pythonhosted.org/packages/e6/f5/80931903275942770f1112b524f1948f6d6ebd44725425025ca838800de2/pydantic-2.7.3-py3-none-any.whl.metadata\n",
      "  Downloading pydantic-2.7.3-py3-none-any.whl.metadata (108 kB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m109.0/109.0 kB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[31m1.4 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting pyproj<4.0.0,>=3.4.0 (from openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for pyproj<4.0.0,>=3.4.0 from https://files.pythonhosted.org/packages/f6/2b/b60cf73b0720abca313bfffef34e34f7f7dae23852b2853cf0368d49426b/pyproj-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading pyproj-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)\n",
      "Collecting traitlets<=5.9.0 (from openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for traitlets<=5.9.0 from https://files.pythonhosted.org/packages/77/75/c28e9ef7abec2b7e9ff35aea3e0be6c1aceaf7873c26c95ae1f0d594de71/traitlets-5.9.0-py3-none-any.whl.metadata\n",
      "  Using cached traitlets-5.9.0-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting rioxarray>=0.13.0 (from openeo)\n",
      "  Obtaining dependency information for rioxarray>=0.13.0 from https://files.pythonhosted.org/packages/88/e0/6c0113291e35a12851007b990cf8f32cc575b4c580c1b5f06715a165849f/rioxarray-0.15.5-py3-none-any.whl.metadata\n",
      "  Using cached rioxarray-0.15.5-py3-none-any.whl.metadata (5.4 kB)\n",
      "Collecting geoparquet<0.0.4,>=0.0.3 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for geoparquet<0.0.4,>=0.0.3 from https://files.pythonhosted.org/packages/27/c3/3ffe3ddc783d3173fe87dbb213bc3b562dd31667662a5c12af100ac77524/geoparquet-0.0.3-py3-none-any.whl.metadata\n",
      "  Using cached geoparquet-0.0.3-py3-none-any.whl.metadata (1.6 kB)\n",
      "Collecting pyarrow<16.0.0,>=15.0.2 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for pyarrow<16.0.0,>=15.0.2 from https://files.pythonhosted.org/packages/e9/0e/0d30e6fd1e0fc9cc267381520f9386a56b2b51c4066d8f9a0d4a5a2e0b44/pyarrow-15.0.2-cp310-cp310-manylinux_2_28_x86_64.whl.metadata\n",
      "  Downloading pyarrow-15.0.2-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)\n",
      "Collecting scipy<2.0.0,>=1.11.3 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for scipy<2.0.0,>=1.11.3 from https://files.pythonhosted.org/packages/a3/ba/7255e5dc82a65adbe83771c72f384d99c43063648456796436c9a5585ec3/scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m60.6/60.6 kB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[31m1.8 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting wrapt<2,>=1.10 (from deprecated>=1.2.12->openeo)\n",
      "  Obtaining dependency information for wrapt<2,>=1.10 from https://files.pythonhosted.org/packages/49/83/b40bc1ad04a868b5b5bcec86349f06c1ee1ea7afe51dc3e46131e4f39308/wrapt-1.16.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading wrapt-1.16.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n",
      "Collecting dask-geopandas<1,>=0.2.0 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for dask-geopandas<1,>=0.2.0 from https://files.pythonhosted.org/packages/49/e2/fe0cbaa1958c9c8635f2b72f8e01672f3fd133033f0dca4f129a92df8621/dask_geopandas-0.3.1-py3-none-any.whl.metadata\n",
      "  Using cached dask_geopandas-0.3.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "Collecting dask[array,dataframe]>=2023.4.0 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for dask[array,dataframe]>=2023.4.0 from https://files.pythonhosted.org/packages/88/ac/9e43c3b495dcbfae583be13b15552fafd53c8f2345fbf0a413950721bb87/dask-2024.5.2-py3-none-any.whl.metadata\n",
      "  Using cached dask-2024.5.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "Collecting geopandas<1,>=0.11.1 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for geopandas<1,>=0.11.1 from https://files.pythonhosted.org/packages/3e/b0/69fa7a0f55122847506a42fea6988d03b34136938082f142151bc9d9f7e7/geopandas-0.14.4-py3-none-any.whl.metadata\n",
      "  Using cached geopandas-0.14.4-py3-none-any.whl.metadata (1.5 kB)\n",
      "Collecting joblib>=1.3.2 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for joblib>=1.3.2 from https://files.pythonhosted.org/packages/91/29/df4b9b42f2be0b623cbd5e2140cafcaa2bef0759a00b7b70104dcfe2fb51/joblib-1.4.2-py3-none-any.whl.metadata\n",
      "  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)\n",
      "Collecting odc-geo<1,>=0.4.1 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for odc-geo<1,>=0.4.1 from https://files.pythonhosted.org/packages/2f/86/2b4abb726aea7cb0f4a55bfb719d378dbfabeb292f0cb3ca57dbdbbe518e/odc_geo-0.4.5-py3-none-any.whl.metadata\n",
      "  Using cached odc_geo-0.4.5-py3-none-any.whl.metadata (5.0 kB)\n",
      "Collecting planetary_computer>=0.5.1 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for planetary_computer>=0.5.1 from https://files.pythonhosted.org/packages/4f/7a/3965a2b58d172e106c1064af19707d29f86a0142c28ff40185490a0a8cfe/planetary_computer-1.0.0-py3-none-any.whl.metadata\n",
      "  Using cached planetary_computer-1.0.0-py3-none-any.whl.metadata (7.4 kB)\n",
      "Collecting pystac_client>=0.6.1 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for pystac_client>=0.6.1 from https://files.pythonhosted.org/packages/e7/be/986fe365d9f0fedb75993da2bfed73ec77d73abbefeaae5b07b45ae6d3b4/pystac_client-0.8.2-py3-none-any.whl.metadata\n",
      "  Using cached pystac_client-0.8.2-py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting rasterio<2.0.0,>=1.3.4 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for rasterio<2.0.0,>=1.3.4 from https://files.pythonhosted.org/packages/cb/87/0cee54776b4a28ba722b8525f16bc3868296fae1e0854251c25096650981/rasterio-1.3.10-cp310-cp310-manylinux2014_x86_64.whl.metadata\n",
      "  Downloading rasterio-1.3.10-cp310-cp310-manylinux2014_x86_64.whl.metadata (14 kB)\n",
      "Collecting stac_validator>=3.3.1 (from openeo-processes-dask)\n",
      "  Using cached stac_validator-3.3.2.tar.gz (22 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Installing backend dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting stackstac>=0.4.3 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for stackstac>=0.4.3 from https://files.pythonhosted.org/packages/c4/70/8cc9bb666a056f85f6197754ffae4e22cce64d9e41f26028f753561ea642/stackstac-0.5.0-py3-none-any.whl.metadata\n",
      "  Using cached stackstac-0.5.0-py3-none-any.whl.metadata (8.0 kB)\n",
      "Collecting xvec>=0.1.0 (from openeo-processes-dask)\n",
      "  Obtaining dependency information for xvec>=0.1.0 from https://files.pythonhosted.org/packages/1e/d3/36dcc5ef8dc0c9964f7afc6633643310104f9caf3a892b010df2eef2ce8d/xvec-0.2.0-py3-none-any.whl.metadata\n",
      "  Using cached xvec-0.2.0-py3-none-any.whl.metadata (2.1 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from pandas>0.20.0->openeo) (2.9.0.post0)\n",
      "Collecting pytz>=2020.1 (from pandas>0.20.0->openeo)\n",
      "  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)\n",
      "Collecting tzdata>=2022.7 (from pandas>0.20.0->openeo)\n",
      "  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)\n",
      "Collecting pytzdata>=2020.1 (from pendulum<3.0.0,>=2.1.2->openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for pytzdata>=2020.1 from https://files.pythonhosted.org/packages/e0/4f/4474bda990ee740a020cbc3eb271925ef7daa7c8444240d34ff62c8442a3/pytzdata-2020.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached pytzdata-2020.1-py2.py3-none-any.whl.metadata (2.3 kB)\n",
      "Collecting annotated-types>=0.4.0 (from pydantic<3.0.0,>=2.4.0->openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for annotated-types>=0.4.0 from https://files.pythonhosted.org/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl.metadata\n",
      "  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)\n",
      "Collecting pydantic-core==2.18.4 (from pydantic<3.0.0,>=2.4.0->openeo-pg-parser-networkx)\n",
      "  Obtaining dependency information for pydantic-core==2.18.4 from https://files.pythonhosted.org/packages/be/44/18eec2ac121e195662ac0f48c9c2a7bc9e2175edf408004b42adfadfc095/pydantic_core-2.18.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading pydantic_core-2.18.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.4.0->openeo-pg-parser-networkx) (4.12.1)\n",
      "Requirement already satisfied: certifi in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from pyproj<4.0.0,>=3.4.0->openeo-pg-parser-networkx) (2024.6.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from requests>=2.26.0->openeo) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from requests>=2.26.0->openeo) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from requests>=2.26.0->openeo) (2.2.1)\n",
      "Requirement already satisfied: packaging in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from rioxarray>=0.13.0->openeo) (24.0)\n",
      "Collecting distributed>=2021.06.0 (from dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for distributed>=2021.06.0 from https://files.pythonhosted.org/packages/51/60/552bd866e23c22666a5fe105d623a36b6c85b7323bf151cafdbf004b3cc2/distributed-2024.5.2-py3-none-any.whl.metadata\n",
      "  Using cached distributed-2024.5.2-py3-none-any.whl.metadata (3.4 kB)\n",
      "Collecting click>=8.1 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for click>=8.1 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata\n",
      "  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting cloudpickle>=1.5.0 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for cloudpickle>=1.5.0 from https://files.pythonhosted.org/packages/96/43/dae06432d0c4b1dc9e9149ad37b4ca8384cf6eb7700cd9215b177b914f0a/cloudpickle-3.0.0-py3-none-any.whl.metadata\n",
      "  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)\n",
      "Collecting fsspec>=2021.09.0 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for fsspec>=2021.09.0 from https://files.pythonhosted.org/packages/8f/df/de2c06b316142063b6ccccc97cdc54185e3af771aa4f056d56f0db0e3466/fsspec-2024.6.0-py3-none-any.whl.metadata\n",
      "  Downloading fsspec-2024.6.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting partd>=1.2.0 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for partd>=1.2.0 from https://files.pythonhosted.org/packages/71/e7/40fb618334dcdf7c5a316c0e7343c5cd82d3d866edc100d98e29bc945ecd/partd-1.4.2-py3-none-any.whl.metadata\n",
      "  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: pyyaml>=5.3.1 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask) (6.0.1)\n",
      "Collecting toolz>=0.10.0 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for toolz>=0.10.0 from https://files.pythonhosted.org/packages/b7/8a/d82202c9f89eab30f9fc05380daae87d617e2ad11571ab23d7c13a29bb54/toolz-0.12.1-py3-none-any.whl.metadata\n",
      "  Using cached toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)\n",
      "Collecting importlib-metadata>=4.13.0 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for importlib-metadata>=4.13.0 from https://files.pythonhosted.org/packages/2d/0a/679461c511447ffaf176567d5c496d1de27cbe34a87df6677d7171b2fbd4/importlib_metadata-7.1.0-py3-none-any.whl.metadata\n",
      "  Using cached importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)\n",
      "Collecting dask-expr<1.2,>=1.1 (from dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for dask-expr<1.2,>=1.1 from https://files.pythonhosted.org/packages/05/6e/e057efb05b9be2970334dbea09ef8fd18f585d24206b4cb15a07aca18375/dask_expr-1.1.2-py3-none-any.whl.metadata\n",
      "  Using cached dask_expr-1.1.2-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting fiona>=1.8.21 (from geopandas<1,>=0.11.1->openeo-processes-dask)\n",
      "  Obtaining dependency information for fiona>=1.8.21 from https://files.pythonhosted.org/packages/b1/7f/06719bc1e1c43b4cd1c6f85e3235ca3013eac94ab0b664b0fce6a0eb6532/fiona-1.9.6-cp310-cp310-manylinux2014_x86_64.whl.metadata\n",
      "  Downloading fiona-1.9.6-cp310-cp310-manylinux2014_x86_64.whl.metadata (50 kB)\n",
      "\u001b[2K     \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m50.2/50.2 kB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[31m4.7 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting affine (from odc-geo<1,>=0.4.1->openeo-processes-dask)\n",
      "  Obtaining dependency information for affine from https://files.pythonhosted.org/packages/0b/f7/85273299ab57117850cc0a936c64151171fac4da49bc6fba0dad984a7c5f/affine-2.4.0-py3-none-any.whl.metadata\n",
      "  Using cached affine-2.4.0-py3-none-any.whl.metadata (4.0 kB)\n",
      "Collecting cachetools (from odc-geo<1,>=0.4.1->openeo-processes-dask)\n",
      "  Obtaining dependency information for cachetools from https://files.pythonhosted.org/packages/fb/2b/a64c2d25a37aeb921fddb929111413049fc5f8b9a4c1aefaffaafe768d54/cachetools-5.3.3-py3-none-any.whl.metadata\n",
      "  Using cached cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)\n",
      "Collecting python-dotenv (from planetary_computer>=0.5.1->openeo-processes-dask)\n",
      "  Obtaining dependency information for python-dotenv from https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl.metadata\n",
      "  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)\n",
      "Requirement already satisfied: six>=1.5 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>0.20.0->openeo) (1.16.0)\n",
      "Requirement already satisfied: attrs in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from rasterio<2.0.0,>=1.3.4->openeo-processes-dask) (23.2.0)\n",
      "Collecting cligj>=0.5 (from rasterio<2.0.0,>=1.3.4->openeo-processes-dask)\n",
      "  Obtaining dependency information for cligj>=0.5 from https://files.pythonhosted.org/packages/73/86/43fa9f15c5b9fb6e82620428827cd3c284aa933431405d1bcf5231ae3d3e/cligj-0.7.2-py3-none-any.whl.metadata\n",
      "  Using cached cligj-0.7.2-py3-none-any.whl.metadata (5.0 kB)\n",
      "Collecting snuggs>=1.4.1 (from rasterio<2.0.0,>=1.3.4->openeo-processes-dask)\n",
      "  Obtaining dependency information for snuggs>=1.4.1 from https://files.pythonhosted.org/packages/cc/0e/d27d6e806d6c0d1a2cfdc5d1f088e42339a0a54a09c3343f7f81ec8947ea/snuggs-1.4.7-py3-none-any.whl.metadata\n",
      "  Using cached snuggs-1.4.7-py3-none-any.whl.metadata (3.4 kB)\n",
      "Collecting click-plugins (from rasterio<2.0.0,>=1.3.4->openeo-processes-dask)\n",
      "  Obtaining dependency information for click-plugins from https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl.metadata\n",
      "  Using cached click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)\n",
      "Requirement already satisfied: setuptools in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from rasterio<2.0.0,>=1.3.4->openeo-processes-dask) (67.7.2)\n",
      "Requirement already satisfied: jsonschema>=3.2.0 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from stac_validator>=3.3.1->openeo-processes-dask) (4.22.0)\n",
      "Requirement already satisfied: jinja2>=2.10.3 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask) (3.1.4)\n",
      "Collecting locket>=1.0.0 (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for locket>=1.0.0 from https://files.pythonhosted.org/packages/db/bc/83e112abc66cd466c6b83f99118035867cecd41802f8d044638aa78a106e/locket-1.0.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)\n",
      "Collecting msgpack>=1.0.0 (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for msgpack>=1.0.0 from https://files.pythonhosted.org/packages/d9/96/a1868dd8997d65732476dfc70fef44d046c1b4dbe36ec1481ab744d87775/msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata\n",
      "  Downloading msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)\n",
      "Requirement already satisfied: psutil>=5.7.2 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask) (5.9.8)\n",
      "Collecting sortedcontainers>=2.0.5 (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for sortedcontainers>=2.0.5 from https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)\n",
      "Collecting tblib>=1.6.0 (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for tblib>=1.6.0 from https://files.pythonhosted.org/packages/9b/87/ce70db7cae60e67851eb94e1a2127d4abb573d3866d2efd302ceb0d4d2a5/tblib-3.0.0-py3-none-any.whl.metadata\n",
      "  Using cached tblib-3.0.0-py3-none-any.whl.metadata (25 kB)\n",
      "Requirement already satisfied: tornado>=6.0.4 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask) (6.4)\n",
      "Collecting zict>=3.0.0 (from distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for zict>=3.0.0 from https://files.pythonhosted.org/packages/80/ab/11a76c1e2126084fde2639514f24e6111b789b0bfa4fc6264a8975c7e1f1/zict-3.0.0-py2.py3-none-any.whl.metadata\n",
      "  Using cached zict-3.0.0-py2.py3-none-any.whl.metadata (899 bytes)\n",
      "Collecting zipp>=0.5 (from importlib-metadata>=4.13.0->dask[array,dataframe]>=2023.4.0->openeo-processes-dask)\n",
      "  Obtaining dependency information for zipp>=0.5 from https://files.pythonhosted.org/packages/20/38/f5c473fe9b90c8debdd29ea68d5add0289f1936d6f923b6b9cc0b931194c/zipp-3.19.2-py3-none-any.whl.metadata\n",
      "  Downloading zipp-3.19.2-py3-none-any.whl.metadata (3.6 kB)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from jsonschema>=3.2.0->stac_validator>=3.3.1->openeo-processes-dask) (2023.12.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from jsonschema>=3.2.0->stac_validator>=3.3.1->openeo-processes-dask) (0.35.1)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from jsonschema>=3.2.0->stac_validator>=3.3.1->openeo-processes-dask) (0.18.1)\n",
      "Collecting pyparsing>=2.1.6 (from snuggs>=1.4.1->rasterio<2.0.0,>=1.3.4->openeo-processes-dask)\n",
      "  Obtaining dependency information for pyparsing>=2.1.6 from https://files.pythonhosted.org/packages/9d/ea/6d76df31432a0e6fdf81681a895f009a4bb47b3c39036db3e1b528191d52/pyparsing-3.1.2-py3-none-any.whl.metadata\n",
      "  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/romeokienzler/gitco/tensorlakehouse-openeo-driver/venv/lib/python3.10/site-packages (from jinja2>=2.10.3->distributed>=2021.06.0->dask-geopandas<1,>=0.2.0->openeo-processes-dask) (2.1.5)\n",
      "Using cached openeo-0.29.0-py3-none-any.whl (254 kB)\n",
      "Using cached openeo_pg_parser_networkx-2024.5.0-py3-none-any.whl (23 kB)\n",
      "Downloading openeo_processes_dask-2024.5.3-py3-none-any.whl (270 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m270.6/270.6 kB\u001b[0m \u001b[31m1.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m01\u001b[0m\n",
      "\u001b[?25hUsing cached openeo_processes-0.0.4-py2.py3-none-any.whl (33 kB)\n",
      "Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)\n",
      "Using cached geojson_pydantic-1.1.0-py3-none-any.whl (8.6 kB)\n",
      "Using cached geoparquet-0.0.3-py3-none-any.whl (4.3 kB)\n",
      "Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)\n",
      "Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m18.2/18.2 MB\u001b[0m \u001b[31m1.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m13.0/13.0 MB\u001b[0m \u001b[31m1.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading pyarrow-15.0.2-cp310-cp310-manylinux_2_28_x86_64.whl (38.3 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m38.3/38.3 MB\u001b[0m \u001b[31m2.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading pydantic-2.7.3-py3-none-any.whl (409 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m409.6/409.6 kB\u001b[0m \u001b[31m3.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading pydantic_core-2.18.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.0/2.0 MB\u001b[0m \u001b[31m3.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m0:01\u001b[0m:01\u001b[0m\n",
      "\u001b[?25hDownloading pyproj-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m8.3/8.3 MB\u001b[0m \u001b[31m3.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m0:01\u001b[0m:01\u001b[0m\n",
      "\u001b[?25hUsing cached pystac-1.10.1-py3-none-any.whl (182 kB)\n",
      "Using cached rioxarray-0.15.5-py3-none-any.whl (60 kB)\n",
      "Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m38.6/38.6 MB\u001b[0m \u001b[31m2.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading shapely-2.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.5 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.5/2.5 MB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[36m0:00:01\u001b[0mm eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hUsing cached traitlets-5.9.0-py3-none-any.whl (117 kB)\n",
      "Using cached xarray-2024.5.0-py3-none-any.whl (1.2 MB)\n",
      "Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)\n",
      "Using cached dask_geopandas-0.3.1-py3-none-any.whl (49 kB)\n",
      "Using cached geopandas-0.14.4-py3-none-any.whl (1.1 MB)\n",
      "Using cached joblib-1.4.2-py3-none-any.whl (301 kB)\n",
      "Using cached odc_geo-0.4.5-py3-none-any.whl (148 kB)\n",
      "Using cached planetary_computer-1.0.0-py3-none-any.whl (14 kB)\n",
      "Using cached pystac_client-0.8.2-py3-none-any.whl (33 kB)\n",
      "Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)\n",
      "Using cached pytzdata-2020.1-py2.py3-none-any.whl (489 kB)\n",
      "Downloading rasterio-1.3.10-cp310-cp310-manylinux2014_x86_64.whl (21.5 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m21.5/21.5 MB\u001b[0m \u001b[31m3.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hUsing cached stackstac-0.5.0-py3-none-any.whl (63 kB)\n",
      "Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)\n",
      "Downloading wrapt-1.16.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (80 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m80.3/80.3 kB\u001b[0m \u001b[31m2.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hUsing cached xvec-0.2.0-py3-none-any.whl (26 kB)\n",
      "Using cached click-8.1.7-py3-none-any.whl (97 kB)\n",
      "Using cached cligj-0.7.2-py3-none-any.whl (7.1 kB)\n",
      "Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)\n",
      "Using cached dask-2024.5.2-py3-none-any.whl (1.2 MB)\n",
      "Using cached dask_expr-1.1.2-py3-none-any.whl (205 kB)\n",
      "Using cached distributed-2024.5.2-py3-none-any.whl (1.0 MB)\n",
      "Downloading fiona-1.9.6-cp310-cp310-manylinux2014_x86_64.whl (15.7 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m15.7/15.7 MB\u001b[0m \u001b[31m2.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m[36m0:00:01\u001b[0m\n",
      "\u001b[?25hUsing cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)\n",
      "Downloading fsspec-2024.6.0-py3-none-any.whl (176 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m176.9/176.9 kB\u001b[0m \u001b[31m2.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m[36m0:00:01\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hUsing cached importlib_metadata-7.1.0-py3-none-any.whl (24 kB)\n",
      "Using cached partd-1.4.2-py3-none-any.whl (18 kB)\n",
      "Using cached snuggs-1.4.7-py3-none-any.whl (5.4 kB)\n",
      "Using cached toolz-0.12.1-py3-none-any.whl (56 kB)\n",
      "Using cached affine-2.4.0-py3-none-any.whl (15 kB)\n",
      "Using cached cachetools-5.3.3-py3-none-any.whl (9.3 kB)\n",
      "Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)\n",
      "Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)\n",
      "Downloading msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (385 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m385.1/385.1 kB\u001b[0m \u001b[31m2.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hUsing cached pyparsing-3.1.2-py3-none-any.whl (103 kB)\n",
      "Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)\n",
      "Using cached tblib-3.0.0-py3-none-any.whl (12 kB)\n",
      "Using cached zict-3.0.0-py2.py3-none-any.whl (43 kB)\n",
      "Downloading zipp-3.19.2-py3-none-any.whl (9.0 kB)\n",
      "Building wheels for collected packages: pendulum, stac_validator\n",
      "  Building wheel for pendulum (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for pendulum: filename=pendulum-2.1.2-cp310-cp310-manylinux_2_38_x86_64.whl size=109781 sha256=8751b51cf9d8392e46f93f6f7f36d509e5259aa8c321d3b15a24267d8a97ef01\n",
      "  Stored in directory: /home/romeokienzler/.cache/pip/wheels/2e/41/ed/f113e4c9dc10f6c846d69f412e9cd9aa429960a3e2e485a4f9\n",
      "  Building wheel for stac_validator (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for stac_validator: filename=stac_validator-3.3.2-py3-none-any.whl size=16406 sha256=888de78288ec37a40d297a3adbab90317ace0377d025d8907e83ad1805037613\n",
      "  Stored in directory: /home/romeokienzler/.cache/pip/wheels/2a/c8/2f/b8e797085c6b50950971ba573ad491ae50489f7952b45618da\n",
      "Successfully built pendulum stac_validator\n",
      "Installing collected packages: sortedcontainers, pytz, geoparquet, zipp, zict, wrapt, tzdata, traitlets, toolz, tblib, pytzdata, python-dotenv, pyproj, pyparsing, pydantic-core, numpy, networkx, msgpack, locket, joblib, fsspec, cloudpickle, click, cachetools, annotated-types, affine, snuggs, shapely, scipy, pystac, pydantic, pyarrow, pendulum, partd, pandas, importlib-metadata, deprecated, cligj, click-plugins, xarray, rasterio, openeo-processes-dask, openeo-processes, odc-geo, geojson-pydantic, fiona, dask, xvec, stac_validator, rioxarray, openeo-pg-parser-networkx, openeo, geopandas, distributed, dask-expr, stackstac, pystac_client, dask-geopandas, planetary_computer\n",
      "  Attempting uninstall: traitlets\n",
      "    Found existing installation: traitlets 5.14.3\n",
      "    Uninstalling traitlets-5.14.3:\n",
      "      Successfully uninstalled traitlets-5.14.3\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "ipython 8.25.0 requires traitlets>=5.13.0, but you have traitlets 5.9.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed affine-2.4.0 annotated-types-0.7.0 cachetools-5.3.3 click-8.1.7 click-plugins-1.1.1 cligj-0.7.2 cloudpickle-3.0.0 dask-2024.5.2 dask-expr-1.1.2 dask-geopandas-0.3.1 deprecated-1.2.14 distributed-2024.5.2 fiona-1.9.6 fsspec-2024.6.0 geojson-pydantic-1.1.0 geopandas-0.14.4 geoparquet-0.0.3 importlib-metadata-7.1.0 joblib-1.4.2 locket-1.0.0 msgpack-1.0.8 networkx-2.8.8 numpy-1.26.4 odc-geo-0.4.5 openeo-0.29.0 openeo-pg-parser-networkx-2024.5.0 openeo-processes-0.0.4 openeo-processes-dask-2024.5.3 pandas-2.2.2 partd-1.4.2 pendulum-2.1.2 planetary_computer-1.0.0 pyarrow-15.0.2 pydantic-2.7.3 pydantic-core-2.18.4 pyparsing-3.1.2 pyproj-3.6.1 pystac-1.10.1 pystac_client-0.8.2 python-dotenv-1.0.1 pytz-2024.1 pytzdata-2020.1 rasterio-1.3.10 rioxarray-0.15.5 scipy-1.13.1 shapely-2.0.4 snuggs-1.4.7 sortedcontainers-2.4.0 stac_validator-3.3.2 stackstac-0.5.0 tblib-3.0.0 toolz-0.12.1 traitlets-5.9.0 tzdata-2024.1 wrapt-1.16.0 xarray-2024.5.0 xvec-0.2.0 zict-3.0.0 zipp-3.19.2\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.2.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.0\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install openeo openeo-pg-parser-networkx openeo[localprocessing] openeo-processes-dask openeo-processes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "3d47ee86-00e6-4dd3-8d61-dc981e127308",
   "metadata": {},
   "outputs": [],
   "source": [
    "from openeo.local import LocalConnection\n",
    "from pathlib import Path\n",
    "import xarray as xr\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "2ba15166-e9a5-4d3e-8bcf-e783a48c05a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "path = '/home/romeokienzler/Downloads/S1A_IW_GRDH_1SDV_20220101T090715_20220101T090740_041265_04E78F_73F0_VH.tif'\n",
    "p = Path(path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6c757128-5110-42ce-a422-1268a0a6b186",
   "metadata": {},
   "outputs": [],
   "source": [
    "local_conn = LocalConnection(p.parent)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "0b6644c0-3d5f-4204-8eaa-4ffd571b6ae1",
   "metadata": {},
   "outputs": [],
   "source": [
    "coll = local_conn.describe_collection(path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "337134c1-85cf-4e52-af41-31748dcc39ba",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'x': {'type': 'spatial',\n",
       "  'axis': 'x',\n",
       "  'extent': [-53.128447512491896, -50.52225521020434],\n",
       "  'reference_system': 'GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"4326\"]]'},\n",
       " 'y': {'type': 'spatial',\n",
       "  'axis': 'y',\n",
       "  'extent': [-6.307796460110961, -4.29404308770023],\n",
       "  'reference_system': 'GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"4326\"]]'},\n",
       " 'bands': {'type': 'bands', 'values': ['band_1']}}"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cube_dimensions = coll[\"cube:dimensions\"]\n",
    "cube_dimensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "b69aa68c-be32-4f94-aa62-0ef89ad7cf7c",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValidationError",
     "evalue": "34 validation errors for ProcessGraph\nprocess_graph.root.arguments.spatial_extent.ResultReference\n  Input should be a valid dictionary or instance of ResultReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.ParameterReference\n  Input should be a valid dictionary or instance of ParameterReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.ProcessGraph\n  Input should be a valid dictionary or instance of ProcessGraph [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.BoundingBox\n  Input should be a valid dictionary or instance of BoundingBox [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.JobId\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.spatial_extent.Year\n  Value error, Could not parse `Year` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.Date\n  Value error, Could not parse `Date` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.DateTime\n  Value error, Could not parse `DateTime` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.Duration\n  Value error, Could not parse `Duration` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.TemporalInterval\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.TemporalIntervals\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.Time\n  Value error, Could not parse `Time` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.float\n  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/float_type\nprocess_graph.root.arguments.spatial_extent.bool\n  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/bool_type\nprocess_graph.root.arguments.spatial_extent.list[any]\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.dict[any,any]\n  Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/dict_type\nprocess_graph.root.arguments.spatial_extent.str\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.temporal_extent.ResultReference\n  Input should be a valid dictionary or instance of ResultReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.ParameterReference\n  Input should be a valid dictionary or instance of ParameterReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.ProcessGraph\n  Input should be a valid dictionary or instance of ProcessGraph [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.BoundingBox\n  Input should be a valid dictionary or instance of BoundingBox [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.JobId\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.temporal_extent.Year\n  Value error, Could not parse `Year` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.Date\n  Value error, Could not parse `Date` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.DateTime\n  Value error, Could not parse `DateTime` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.Duration\n  Value error, Could not parse `Duration` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.TemporalInterval\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.TemporalIntervals\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.Time\n  Value error, Could not parse `Time` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.float\n  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/float_type\nprocess_graph.root.arguments.temporal_extent.bool\n  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/bool_type\nprocess_graph.root.arguments.temporal_extent.list[any]\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.dict[any,any]\n  Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/dict_type\nprocess_graph.root.arguments.temporal_extent.str\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValidationError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[21], line 14\u001b[0m\n\u001b[1;32m     12\u001b[0m         coords\u001b[38;5;241m.\u001b[39mappend([lon, lat])\n\u001b[1;32m     13\u001b[0m datacube \u001b[38;5;241m=\u001b[39m local_conn\u001b[38;5;241m.\u001b[39mload_collection(path)\n\u001b[0;32m---> 14\u001b[0m data: xr\u001b[38;5;241m.\u001b[39mDataArray \u001b[38;5;241m=\u001b[39m \u001b[43mdatacube\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/gitco/tensorlakehouse-openeo-driver/venv/lib64/python3.10/site-packages/openeo/rest/datacube.py:2335\u001b[0m, in \u001b[0;36mDataCube.execute\u001b[0;34m(self, validate, auto_decode)\u001b[0m\n\u001b[1;32m   2325\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mexecute\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39m, validate: Optional[\u001b[38;5;28mbool\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m, auto_decode: \u001b[38;5;28mbool\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Union[\u001b[38;5;28mdict\u001b[39m, requests\u001b[38;5;241m.\u001b[39mResponse]:\n\u001b[1;32m   2326\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   2327\u001b[0m \u001b[38;5;124;03m    Execute a process graph synchronously and return the result. If the result is a JSON object, it will be parsed.\u001b[39;00m\n\u001b[1;32m   2328\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   2333\u001b[0m \u001b[38;5;124;03m    :return: parsed JSON response as a dict if auto_decode is True, otherwise response object\u001b[39;00m\n\u001b[1;32m   2334\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 2335\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_connection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mflat_graph\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalidate\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mvalidate\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mauto_decode\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mauto_decode\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/gitco/tensorlakehouse-openeo-driver/venv/lib64/python3.10/site-packages/openeo/local/connection.py:285\u001b[0m, in \u001b[0;36mLocalConnection.execute\u001b[0;34m(self, process_graph, validate, auto_decode)\u001b[0m\n\u001b[1;32m    283\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mLocalConnection requires auto_decode=True\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m    284\u001b[0m process_graph \u001b[38;5;241m=\u001b[39m as_flat_graph(process_graph)\n\u001b[0;32m--> 285\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mOpenEOProcessGraph\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprocess_graph\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241m.\u001b[39mto_callable(PROCESS_REGISTRY)()\n",
      "File \u001b[0;32m~/gitco/tensorlakehouse-openeo-driver/venv/lib64/python3.10/site-packages/openeo_pg_parser_networkx/graph.py:79\u001b[0m, in \u001b[0;36mOpenEOProcessGraph.__init__\u001b[0;34m(self, pg_data)\u001b[0m\n\u001b[1;32m     76\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpg_data \u001b[38;5;241m=\u001b[39m pg_data\n\u001b[1;32m     78\u001b[0m nested_raw_graph \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_unflatten_raw_process_graph(pg_data)\n\u001b[0;32m---> 79\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnested_graph \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_parse_datamodel\u001b[49m\u001b[43m(\u001b[49m\u001b[43mnested_raw_graph\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     81\u001b[0m \u001b[38;5;66;03m# Start parsing the graph at the result node of the top-level graph.\u001b[39;00m\n\u001b[1;32m     82\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_EVAL_ENV \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/gitco/tensorlakehouse-openeo-driver/venv/lib64/python3.10/site-packages/openeo_pg_parser_networkx/graph.py:116\u001b[0m, in \u001b[0;36mOpenEOProcessGraph._parse_datamodel\u001b[0;34m(nested_graph)\u001b[0m\n\u001b[1;32m    110\u001b[0m \u001b[38;5;129m@staticmethod\u001b[39m\n\u001b[1;32m    111\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_parse_datamodel\u001b[39m(nested_graph: \u001b[38;5;28mdict\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m ProcessGraph:\n\u001b[1;32m    112\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m    113\u001b[0m \u001b[38;5;124;03m    Parses a nested process graph into the Pydantic datamodel for ProcessGraph.\u001b[39;00m\n\u001b[1;32m    114\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 116\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mProcessGraph\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmodel_validate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mnested_graph\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/gitco/tensorlakehouse-openeo-driver/venv/lib64/python3.10/site-packages/pydantic/main.py:551\u001b[0m, in \u001b[0;36mBaseModel.model_validate\u001b[0;34m(cls, obj, strict, from_attributes, context)\u001b[0m\n\u001b[1;32m    549\u001b[0m \u001b[38;5;66;03m# `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks\u001b[39;00m\n\u001b[1;32m    550\u001b[0m __tracebackhide__ \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n\u001b[0;32m--> 551\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mcls\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__pydantic_validator__\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvalidate_python\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    552\u001b[0m \u001b[43m    \u001b[49m\u001b[43mobj\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstrict\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstrict\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfrom_attributes\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfrom_attributes\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcontext\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcontext\u001b[49m\n\u001b[1;32m    553\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mValidationError\u001b[0m: 34 validation errors for ProcessGraph\nprocess_graph.root.arguments.spatial_extent.ResultReference\n  Input should be a valid dictionary or instance of ResultReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.ParameterReference\n  Input should be a valid dictionary or instance of ParameterReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.ProcessGraph\n  Input should be a valid dictionary or instance of ProcessGraph [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.BoundingBox\n  Input should be a valid dictionary or instance of BoundingBox [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.spatial_extent.JobId\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.spatial_extent.Year\n  Value error, Could not parse `Year` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.Date\n  Value error, Could not parse `Date` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.DateTime\n  Value error, Could not parse `DateTime` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.Duration\n  Value error, Could not parse `Duration` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.TemporalInterval\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.TemporalIntervals\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.Time\n  Value error, Could not parse `Time` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.spatial_extent.float\n  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/float_type\nprocess_graph.root.arguments.spatial_extent.bool\n  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/bool_type\nprocess_graph.root.arguments.spatial_extent.list[any]\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.spatial_extent.dict[any,any]\n  Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/dict_type\nprocess_graph.root.arguments.spatial_extent.str\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.temporal_extent.ResultReference\n  Input should be a valid dictionary or instance of ResultReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.ParameterReference\n  Input should be a valid dictionary or instance of ParameterReference [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.ProcessGraph\n  Input should be a valid dictionary or instance of ProcessGraph [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.BoundingBox\n  Input should be a valid dictionary or instance of BoundingBox [type=model_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/model_type\nprocess_graph.root.arguments.temporal_extent.JobId\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type\nprocess_graph.root.arguments.temporal_extent.Year\n  Value error, Could not parse `Year` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.Date\n  Value error, Could not parse `Date` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.DateTime\n  Value error, Could not parse `DateTime` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.Duration\n  Value error, Could not parse `Duration` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.TemporalInterval\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.TemporalIntervals\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.Time\n  Value error, Could not parse `Time` from input. [type=value_error, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error\nprocess_graph.root.arguments.temporal_extent.float\n  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/float_type\nprocess_graph.root.arguments.temporal_extent.bool\n  Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/bool_type\nprocess_graph.root.arguments.temporal_extent.list[any]\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/list_type\nprocess_graph.root.arguments.temporal_extent.dict[any,any]\n  Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/dict_type\nprocess_graph.root.arguments.temporal_extent.str\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.7/v/string_type"
     ]
    }
   ],
   "source": [
    "\n",
    "for dim_name, dim_info in cube_dimensions.items():\n",
    "    if dim_info.get(\"axis\") is not None:\n",
    "        if dim_info.get(\"axis\") == 'x': \n",
    "            west = dim_info[\"extent\"][0]\n",
    "            east = dim_info[\"extent\"][1]\n",
    "        if dim_info.get(\"axis\") == 'y': \n",
    "            south = dim_info[\"extent\"][0]\n",
    "            north = dim_info[\"extent\"][1]\n",
    "coords = list()\n",
    "for lat in [south, north]:\n",
    "    for lon in [west, east]:\n",
    "        coords.append([lon, lat])\n",
    "datacube = local_conn.load_collection(path)\n",
    "data: xr.DataArray = datacube.execute()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99e93e47-4699-4fa6-99ee-6603018b3a7c",
   "metadata": {},
   "outputs": [],
   "source": [
    "from openeo.local import LocalConnection\n",
    "from pathlib import Path\n",
    "import pytest\n",
    "import xarray as xr\n",
    "\n",
    "from tensorlakehouse_openeo_driver.constants import DEFAULT_X_DIMENSION, DEFAULT_Y_DIMENSION\n",
    "\n",
    "# from tensorlakehouse_openeo_driver.local.connection import GeodnLocalConnection\n",
    "\n",
    "\n",
    "@pytest.mark.parametrize(\n",
    "    \"path\",\n",
    "    [\n",
    "        \"/Users/ltizzei/Projects/Orgs/IBM/tensorlakehouse-openeo-driver/tensorlakehouse_openeo_driver/tests/test_data/test_openeo_Globalweather-ERA5-.nc\",\n",
    "        \"/Users/ltizzei/Projects/Orgs/IBM/tensorlakehouse-openeo-driver/tensorlakehouse_openeo_driver/tests/test_data/tasmax_rcp85_land-cpm_uk_2.2km/tasmax_rcp85_land-cpm_uk_2.2km_01_day_20701201-20711130_reproj.nc\",\n",
    "    ],\n",
    ")\n",
    "def test_local_connection(path: str):\n",
    "    p = Path(path)\n",
    "    assert p.exists(), f\"Error! File does not exist {p}\"\n",
    "\n",
    "    local_conn = LocalConnection(p.parent)\n",
    "\n",
    "    # list_collections = local_conn.list_collections()\n",
    "    coll = local_conn.describe_collection(path)\n",
    "    cube_dimensions = coll[\"cube:dimensions\"]\n",
    "    temporal_dim_name = None\n",
    "    for dim_name, dim_info in cube_dimensions.items():\n",
    "        if dim_info.get(\"axis\") is not None:\n",
    "            if dim_info.get(\"axis\") == DEFAULT_X_DIMENSION: \n",
    "                west = dim_info[\"extent\"][0]\n",
    "                east = dim_info[\"extent\"][1]\n",
    "            if dim_info.get(\"axis\") == DEFAULT_Y_DIMENSION: \n",
    "                south = dim_info[\"extent\"][0]\n",
    "                north = dim_info[\"extent\"][1]\n",
    "        elif dim_info.get(\"type\") == \"temporal\":\n",
    "            temporal_dim_name = dim_name\n",
    "    coords = list()\n",
    "    for lat in [south, north]:\n",
    "        for lon in [west, east]:\n",
    "            coords.append([lon, lat])\n",
    "    datacube = local_conn.load_collection(path)\n",
    "    datacube = datacube.reduce_dimension(dimension=temporal_dim_name, reducer=\"mean\")\n",
    "    data: xr.DataArray = datacube.execute()\n",
    "    assert isinstance(data, xr.DataArray)\n",
    "    assert temporal_dim_name not in data.dims"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5e0039a-c170-4304-9e3d-1750b13d35de",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
